services:
  flux-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flux-app
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
      - flux-archives:/app/storage/app/archives
    environment:
      - APP_ENV=local
      - XDG_CONFIG_HOME=/tmp
    depends_on:
      - flux-db
      - flux-redis
    networks:
      - flux-network
    command: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --admin-port=2021 --watch

  flux-scheduler:
    build: .
    container_name: flux-scheduler
    restart: always
    volumes:
      - .:/app
      - flux-archives:/app/storage/app/archives
    networks:
      - flux-network
    depends_on:
      - flux-app
    command: php artisan schedule:work

  flux-db:
    image: postgres:18-alpine
    container_name: flux-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=flux_db
      - POSTGRES_USER=flux_user
      - POSTGRES_PASSWORD=flux_pass
    volumes:
      - flux-db-data:/var/lib/postgresql/data
    networks:
      - flux-network

  flux-redis:
    image: redis:alpine
    container_name: flux-redis
    networks:
      - flux-network

  flux-reverb:
    build: .
    container_name: flux-reverb
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - flux-network
    depends_on:
      - flux-app
    command: php artisan reverb:start --host=0.0.0.0 --port=8080 --debug

  flux-worker:
    build: .
    container_name: flux-worker
    restart: always
    volumes:
      - .:/app
    networks:
      - flux-network
    depends_on:
      - flux-app
      - flux-redis
    command: php artisan queue:work

networks:
  flux-network:
    driver: bridge

volumes:
  flux-db-data:
  flux-archives:
